apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: python-demo
  namespace: flux-system
spec:
  image: mucker67/python-demo
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: python-demo-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: python-demo
  policy:
    semver:
      range: ">=0.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: python-demo-automation
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: nibbles
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: Flux Bot
        email: flux@example.com
      messageTemplate: "Update image to {{ .NewImage }}"
    push:
      branch: main
  update:
    path: "./k3s"
    strategy: Setters
