apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: python-demo
  namespace: flux-system
spec:
  image: mucker67/python-demo
  interval: 1m
ImagePolicy
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: python-demo-policy
  namespace: flux-system
spec:
  filterTags:
    pattern: '^build-(?P<build>\\d+)$'
    extract: '$build'
  policy:
    numerical:
      order: asc
  imageRepositoryRef:
    name: python-demo