name: build-and-push

on:
  push:
    branches: ["main"]
    # Verhindert, dass der Workflow bei Änderungen an den Deployment-Files startet
    paths-ignore:
      - 'k3s/**'       # Ignoriere alles im k3s Ordner (wo Flux die Tags ändert)
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Schritt: QEMU installieren (ermöglicht das Bauen für andere CPUs)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 2. Schritt: Docker Buildx einrichten
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          # 3. Schritt: Hier definierst du die Ziel-Architekturen
          # linux/amd64 = PC, linux/arm64 = Raspberry Pi (64-bit)
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mucker67/python-demo:build-${{ github.run_number }}